# Generated by Django 5.1.1 on 2024-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=1000)),
                ('news_text', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=150)),
            ],
        ),
    ]
